spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://101.43.253.49:3306/free-fs?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: Elites2134593
    driver-class-name: com.mysql.cj.jdbc.Driver

#开启演示环境，控制所有接口
fs:
  isPreview: true
