name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Dependies Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn clean package --file pom.xml
      - name: Transfer jar packets
        uses: garygrossgarten/github-action-scp@release
        with:
          local: target/free-fs.jar
          remote: /data/free-fs/free-fs.jar
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /data/free-fs
            ps -ef | grep  free-fs.jar | grep -v grep | awk '{print $2}' | xargs kill -9
            nohup /usr/local/java/graalvm-ce-java17-22.3.1/bin/java -jar /data/free-fs/free-fs.jar > runtime.log 2>&1 &
            pwd
